blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/samdoesnerdstuff/lambda/discussions
    about: "For open-ended conversations, brainstorming, and design talk."